pipeline{
    agent any

    stages {
        stage('Run Dagger function tofu-init') {
            steps {
                withCredentials([
                    string(credentialsId: 'infracost-api-key', variable: 'INFRACOST_API_KEY'),
                    string(credentialsId: 'ssh-private-key', variable: 'SSH_PRIVATE_KEY'),
                    string(credentialsId: 'ssh-public-key', variable: 'SSH_PUBLIC_KEY'),
                    file(credentialsId: 'gcp-api-key', variable: 'GCP_KEY_FILE')
                ]){
                    sh """
                    cd "$WORKSPACE/iac-pipeline"
                    pwd
                    export INFRACOST_API_KEY="${INFRACOST_API_KEY}"
                    export SSH_PRIVATE_KEY="${SSH_PRIVATE_KEY}"
                    export SSH_PUBLIC_KEY="${SSH_PUBLIC_KEY}"
                    export GCP_CREDENTIALS=\$(cat "\$GCP_KEY_FILE")

                    dagger call tofu-init \\
                    --src=../iac/gcloud \\
                    --budget-eur=40 \\
                    --infracost-api-key=env:INFRACOST_API_KEY \\
                    --ssh-private-key=env:SSH_PRIVATE_KEY \\
                    --ssh-public-key=env:SSH_PUBLIC_KEY \\
                    --gcp_sa_key=env:GCP_CREDENTIALS \\
                    --output $WORKSPACE/tofu-inits
                    """
                }
            }
        }
    }
}